spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.119:3306/mysell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

server:
  servlet:
    context-path: /sell

wechat:
  mpAppId: wx33b4127ac677deda
  mpAppSecret: 4fba115888e58753f6539a4e8d1af91e

project-url:
  wechatMpAuthorize: http://6jmsi8.natappfree.cc
  wechatOpenAuthorize: http://6jmsi8.natappfree.cc
  sell: http://6jmsi8.natappfree.cc
